# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_1/design_1_rst_mig_7series_0_100M_1.xci
# IP: The module: 'design_1_rst_mig_7series_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_1/design_1_rst_mig_7series_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_mig_7series_0_100M_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_1/design_1_rst_mig_7series_0_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_mig_7series_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_1/design_1_rst_mig_7series_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_mig_7series_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_1/design_1_rst_mig_7series_0_100M_1.xci
# IP: The module: 'design_1_rst_mig_7series_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_1/design_1_rst_mig_7series_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_mig_7series_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_1/design_1_rst_mig_7series_0_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_mig_7series_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_1/design_1_rst_mig_7series_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_mig_7series_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
