# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_0/bd_929b_eth_buf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_929b_eth_buf_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_929b_eth_buf_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_929b_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_0/bd_929b_eth_buf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_929b_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_0/bd_929b_eth_buf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_929b_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_929b_eth_buf_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_929b_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/Microblaze_2018R2_20200318_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_0/bd_929b_eth_buf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_929b_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
